Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,9 @@ jobs:
       - name: Run a one-line script
         run: echo Hello, world!
 
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
